Repository FlytrapHub/RSS-Reader, pull requests merged in 2023-12, with the labels that each got.

#101 포스트 열림 상태 삭제 기능 구현
  src/main/java/com/flytrap/rssreader/domain/folder/Folder.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/SubscribeEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/Folders.java
  src/main/java/com/flytrap/rssreader/service/FolderVerifyOwnerService.java
  src/main/java/com/flytrap/rssreader/service/PostOpenEventHandler.java
  src/main/java/com/flytrap/rssreader/service/PostOpenService.java
  src/main/java/com/flytrap/rssreader/service/SubscribeService.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#104 폴더 보기 리팩토링
  src/main/java/com/flytrap/rssreader/domain/folder/Folder.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/OpenPostCount.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/SubscribePostCount.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostOpenRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostReadController.java
  src/main/java/com/flytrap/rssreader/presentation/facade/InvitedToFolderFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/MyFolderFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/OpenCheckFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/SubscribeInFolderFacade.java
  src/main/java/com/flytrap/rssreader/service/PostOpenService.java
  src/main/java/com/flytrap/rssreader/service/PostReadService.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#105 Post Entity 연관관계 제거
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadDslRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/output/PostOutput.java
  src/main/java/com/flytrap/rssreader/service/BookmarkService.java
  src/main/java/com/flytrap/rssreader/service/PostListReadService.java
  src/main/java/com/flytrap/rssreader/service/PostReadService.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#108 전체 게시글 리스트 반환 시 공유폴더의 게시글도 반환하도록 변경
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadDslRepository.java
  src/main/java/com/flytrap/rssreader/presentation/dto/PostResponse.java
  src/main/resources/db/data.sql
Labels: 🧑🏻‍💻 backend, ✨ feature

#109 #96 리뷰 반영: pubDate 포맷 변환 로직 변경
  src/main/java/com/flytrap/rssreader/global/utill/DateConvertor.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#110 alert 알림 서비스 리팩토링, 테스트 코드 작성
  src/main/java/com/flytrap/rssreader/domain/alert/SubscribeEvent.java
  src/main/java/com/flytrap/rssreader/domain/alert/q/SubscribeEventListener.java
  src/main/java/com/flytrap/rssreader/domain/alert/q/SubscribeEventPublisher.java
  src/main/java/com/flytrap/rssreader/domain/alert/q/SubscribeEventQueue.java
  src/main/java/com/flytrap/rssreader/domain/alert/q/SubscribeEventWorker.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostOpenRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostUpdateController.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/java/com/flytrap/rssreader/service/alert/AlertEventHandler.java
  src/main/java/com/flytrap/rssreader/service/alert/AlertFacadeService.java
  src/main/java/com/flytrap/rssreader/service/alert/AlertService.java
  src/main/java/com/flytrap/rssreader/service/alert/platform/AlarmService.java
  src/main/java/com/flytrap/rssreader/service/alert/platform/SlackAlarmService.java
  src/main/java/com/flytrap/rssreader/service/dto/AlertParam.java
  src/test/java/com/flytrap/rssreader/domain/SubscribeEventListenerTest.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFields.java
  src/test/java/com/flytrap/rssreader/service/AlertFacadeServiceTest.java
  src/test/java/com/flytrap/rssreader/service/AlertServiceTest.java
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#113 인프라 구축 파일 초안 작성
  Dockerfile
  docker-compose.yml
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/facade/MyFolderFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/SubscribeInFolderFacade.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderReadService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderSubscribeService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderUpdateService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderVerifyOwnerService.java
  src/test/java/com/flytrap/rssreader/service/FolderUpdateServiceTest.java
  src/test/java/com/flytrap/rssreader/service/FolderVerifyOwnerServiceTest.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#117 1차 배포 파이프라인 구축
  .github/workflows/ deploy-to-ec2.yml
  docker-compose.yml
  nginx/conf.d
  run.sh
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#118 Release Test
  .github/workflows/ deploy-to-ec2.yml
  Dockerfile
  docker-compose.yml
  nginx/conf.d
  run.sh
  src/main/java/com/flytrap/rssreader/domain/alert/SubscribeEvent.java
  src/main/java/com/flytrap/rssreader/domain/alert/q/SubscribeEventListener.java
  src/main/java/com/flytrap/rssreader/domain/alert/q/SubscribeEventPublisher.java
  src/main/java/com/flytrap/rssreader/domain/alert/q/SubscribeEventQueue.java
  src/main/java/com/flytrap/rssreader/domain/alert/q/SubscribeEventWorker.java
  src/main/java/com/flytrap/rssreader/global/utill/DateConvertor.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadDslRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/output/PostOutput.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/PostResponse.java
  src/main/java/com/flytrap/rssreader/presentation/facade/MyFolderFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/SubscribeInFolderFacade.java
  src/main/java/com/flytrap/rssreader/service/BookmarkService.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/java/com/flytrap/rssreader/service/PostListReadService.java
  src/main/java/com/flytrap/rssreader/service/PostReadService.java
  src/main/java/com/flytrap/rssreader/service/alert/AlertEventHandler.java
  src/main/java/com/flytrap/rssreader/service/alert/AlertFacadeService.java
  src/main/java/com/flytrap/rssreader/service/alert/AlertService.java
  src/main/java/com/flytrap/rssreader/service/alert/platform/AlarmService.java
  src/main/java/com/flytrap/rssreader/service/alert/platform/SlackAlarmService.java
  src/main/java/com/flytrap/rssreader/service/dto/AlertParam.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderReadService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderSubscribeService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderUpdateService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderVerifyOwnerService.java
  src/main/resources/application.yml
  src/main/resources/db/data.sql
  src/test/java/com/flytrap/rssreader/domain/SubscribeEventListenerTest.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFields.java
  src/test/java/com/flytrap/rssreader/service/AlertFacadeServiceTest.java
  src/test/java/com/flytrap/rssreader/service/AlertServiceTest.java
  src/test/java/com/flytrap/rssreader/service/FolderUpdateServiceTest.java
  src/test/java/com/flytrap/rssreader/service/FolderVerifyOwnerServiceTest.java
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
Labels: 🧑🏻‍💻 backend, ✅ test

#122 배포 페이지 CORS 설정
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#125 Swagger 문서용 Api Interface 뼈대 추가
  build.gradle
  src/main/java/com/flytrap/rssreader/presentation/controller/AdminController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/AuthController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/BookmarkController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/MemberController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/AdminControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/AuthControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/BookmarkControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/FolderReadControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/FolderUpdateControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/MemberControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/PostListReadControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/PostReadControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/PostUpdateControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/SharedFolderUpdateControllerApi.java
Labels: 🧑🏻‍💻 backend, 📃 documentation

#128 Folder 리스트 조회 API 호출 중 Null point Exception 해결
  build.gradle
  src/main/java/com/flytrap/rssreader/domain/subscribe/Subscribe.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/FolderReadControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/dto/Folders.java
  src/main/java/com/flytrap/rssreader/presentation/facade/InvitedToFolderFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/OpenCheckFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/SubscribeInFolderFacade.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderSubscribeService.java
  src/test/java/com/flytrap/rssreader/fixture/FolderFixtureFactory.java
  src/test/java/com/flytrap/rssreader/fixture/SubscribeFixtureFactory.java
  src/test/java/com/flytrap/rssreader/presentation/facade/InvitedToFolderFacadeTest.java
  src/test/java/com/flytrap/rssreader/presentation/facade/SubscribeInFolderFacadeTest.java
Labels: 🧑🏻‍💻 backend, 🚨 bug

#130 20203-12-12(화) 배포용 머지 (2차)
  build.gradle
  src/main/java/com/flytrap/rssreader/domain/subscribe/Subscribe.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/FolderReadControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/dto/Folders.java
  src/main/java/com/flytrap/rssreader/presentation/facade/InvitedToFolderFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/OpenCheckFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/SubscribeInFolderFacade.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderSubscribeService.java
  src/test/java/com/flytrap/rssreader/fixture/FolderFixtureFactory.java
  src/test/java/com/flytrap/rssreader/fixture/SubscribeFixtureFactory.java
  src/test/java/com/flytrap/rssreader/presentation/facade/InvitedToFolderFacadeTest.java
  src/test/java/com/flytrap/rssreader/presentation/facade/SubscribeInFolderFacadeTest.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#132 CloudFront CORS 설정 추가
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#133 2023-12-12(화) 클라우드 프론트 테스트용 배포
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#140 사용자 조회가 여러건 일 경우, Duplicate Id Query Exception 수정
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostOpenRepository.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderSubscribeService.java
  src/test/java/com/flytrap/rssreader/service/PostOpenServiceTest.java
Labels: 🧑🏻‍💻 backend, 🚨 bug

#138 북마크 추가/제거 API 변경: 북마크 추가/제거 시 postId를 사용하도록 변경
  src/main/java/com/flytrap/rssreader/infrastructure/repository/BookmarkEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostOpenRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/BookmarkController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/BookmarkControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/dto/BookmarkRequest.java
  src/main/java/com/flytrap/rssreader/service/BookmarkService.java
  src/main/resources/db/data.sql
Labels: 🧑🏻‍💻 backend, ✨ feature
