Repository FlytrapHub/RSS-Reader, pull requests merged in 2023-11, with the labels that each got.

#18 Global session 이용을 위한 Redis 환경설정
  build.gradle
  src/main/resources/application-local.yml
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#19 Member API 일부 구현 - 로그인, 로그아웃 (미완성)
  build.gradle
  src/main/java/com/flytrap/rssreader/config/PropertiesScanConfig.java
  src/main/java/com/flytrap/rssreader/config/WebClientConfig.java
  src/main/java/com/flytrap/rssreader/domain/member/Member.java
  src/main/java/com/flytrap/rssreader/global/model/ApplicationResponse.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/AuthGithubProvider.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/AuthProvider.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/AccessToken.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/UserResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/member/MemberEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/member/OauthServer.java
  src/main/java/com/flytrap/rssreader/infrastructure/properties/OauthProperties.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/MemberEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/AuthController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/MemberController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/Login.java
  src/main/java/com/flytrap/rssreader/service/AuthService.java
  src/main/java/com/flytrap/rssreader/service/MemberService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/db/schema.sql
  src/test/java/com/flytrap/rssreader/service/AuthServiceTest.java
  src/test/java/com/flytrap/rssreader/service/MemberServiceTest.java
Labels: 🧑🏻‍💻 backend, ✅ test, ✨ feature, 🛠 setting

#20 session timeout 증가
  src/main/resources/application-local.yml
Labels: 🧑🏻‍💻 backend, 🛠 setting

#28 Member API 통합테스트 후 디버깅
  .gitignore
  src/main/java/com/flytrap/rssreader/RssReaderApplication.java
  src/main/java/com/flytrap/rssreader/config/WebClientConfig.java
  src/main/java/com/flytrap/rssreader/domain/member/Member.java
  src/main/java/com/flytrap/rssreader/global/model/ApplicationResponse.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/AuthGithubProvider.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/AccessToken.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/UserEmailResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/UserResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/properties/OauthProperties.java
  src/main/java/com/flytrap/rssreader/presentation/controller/AuthController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/Login.java
  src/main/java/com/flytrap/rssreader/service/AuthService.java
  src/main/java/com/flytrap/rssreader/service/MemberService.java
Labels: 🧑🏻‍💻 backend, 🚨 bug, ♻️ refactor

#31 Member API 변경 후 깨진 Test 수정 (#30)
  src/main/java/com/flytrap/rssreader/presentation/dto/Login.java
  src/test/java/com/flytrap/rssreader/service/AuthServiceTest.java
  src/test/java/com/flytrap/rssreader/service/MemberServiceTest.java
Labels: 🧑🏻‍💻 backend, ✅ test, 🚨 bug

#32 RSS 페이지 파싱 후 Post를 저장하는 스케쥴 기능 추가
  src/main/java/com/flytrap/rssreader/RssReaderApplication.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssPostParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssItemResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssItemTagName.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/member/MemberEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/BlogPlatform.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/SubscribeEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/resources/application-local.yml
  src/main/resources/db/data.sql
  src/main/resources/db/schema.sql
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#34 회원 이름으로 검색 구현
  src/main/java/com/flytrap/rssreader/domain/member/Member.java
  src/main/java/com/flytrap/rssreader/domain/member/OauthInfo.java
  src/main/java/com/flytrap/rssreader/domain/member/OauthServer.java
  src/main/java/com/flytrap/rssreader/global/config/PropertiesScanConfig.java
  src/main/java/com/flytrap/rssreader/global/config/WebClientConfig.java
  src/main/java/com/flytrap/rssreader/global/exception/GlobalExceptionHandler.java
  src/main/java/com/flytrap/rssreader/global/exception/NoSuchDomainException.java
  src/main/java/com/flytrap/rssreader/global/model/DefaultDomain.java
  src/main/java/com/flytrap/rssreader/global/model/Domain.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/UserResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/member/MemberEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/member/OauthServer.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/MemberEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/MemberController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/MemberSummary.java
  src/main/java/com/flytrap/rssreader/presentation/dto/NameSearch.java
  src/main/java/com/flytrap/rssreader/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/flytrap/rssreader/service/AuthServiceTest.java
  src/test/java/com/flytrap/rssreader/service/MemberServiceTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#42 PR #32 리뷰반영 - 게시글 파싱 로직 수정
  src/main/java/com/flytrap/rssreader/domain/subscribe/BlogPlatform.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssPostParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssItemResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/BlogPlatform.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFields.java
  src/test/java/com/flytrap/rssreader/service/AuthServiceTest.java
  src/test/java/com/flytrap/rssreader/service/MemberServiceTest.java
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#41 로그인 상태 검증을 위한 Presentation 계층 구현
  src/main/java/com/flytrap/rssreader/domain/member/OauthInfo.java
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
  src/main/java/com/flytrap/rssreader/infrastructure/properties/AdminProperties.java
  src/main/java/com/flytrap/rssreader/infrastructure/properties/AuthProperties.java
  src/main/java/com/flytrap/rssreader/presentation/controller/AdminController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/AuthController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/SessionMember.java
  src/main/java/com/flytrap/rssreader/presentation/filter/AuthenticationFilter.java
  src/main/java/com/flytrap/rssreader/presentation/filter/ExceptionHandleFilter.java
  src/main/java/com/flytrap/rssreader/presentation/resolver/AuthorizationArgumentResolver.java
  src/main/java/com/flytrap/rssreader/presentation/resolver/AuthorizationContext.java
  src/main/java/com/flytrap/rssreader/presentation/resolver/Login.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#43 폴더 생성 API구현
  build.gradle
  src/main/java/com/flytrap/rssreader/domain/folder/Folder.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/folder/FolderEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/properties/AuthProperties.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/FolderEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/FolderCreate.java
  src/main/java/com/flytrap/rssreader/presentation/filter/AuthenticationFilter.java
  src/main/java/com/flytrap/rssreader/presentation/filter/ExceptionHandleFilter.java
  src/main/java/com/flytrap/rssreader/service/AuthService.java
  src/main/java/com/flytrap/rssreader/service/FolderService.java
  src/main/resources/application.yml
  src/main/resources/db/schema.sql
Labels: 🧑🏻‍💻 backend, ✨ feature

#50 PR #32 리뷰반영 - 게시글 수집 작업을 비동기 작업으로 변경
  src/main/java/com/flytrap/rssreader/RssReaderApplication.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/resources/db/data.sql
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#51 32번 리뷰 sprint로 머지
  src/main/java/com/flytrap/rssreader/RssReaderApplication.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/resources/db/data.sql
Labels: 🧑🏻‍💻 backend, 🛠 setting

#53 CORS 설정 및 기타 설정 수정
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
  src/main/java/com/flytrap/rssreader/service/AuthService.java
  src/main/resources/application.yml
  src/main/resources/db/schema.sql
Labels: 🧑🏻‍💻 backend, 🛠 setting

#54 폴더 이름 수정삭제 기능 구현&테스트 / Application Exception 메시지 출력 방식 수정
  src/main/java/com/flytrap/rssreader/domain/folder/Folder.java
  src/main/java/com/flytrap/rssreader/domain/folder/SharedStatus.java
  src/main/java/com/flytrap/rssreader/global/exception/ApplicationException.java
  src/main/java/com/flytrap/rssreader/global/exception/GlobalExceptionHandler.java
  src/main/java/com/flytrap/rssreader/global/exception/NoSuchDomainException.java
  src/main/java/com/flytrap/rssreader/global/exception/NotBelongToMemberException.java
  src/main/java/com/flytrap/rssreader/global/model/ErrorResponse.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/folder/FolderEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/FolderEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/FolderRequest.java
  src/main/java/com/flytrap/rssreader/service/FolderService.java
  src/main/resources/db/schema.sql
  src/test/java/com/flytrap/rssreader/fixture/FolderFixtureFactory.java
  src/test/java/com/flytrap/rssreader/service/AuthServiceTest.java
  src/test/java/com/flytrap/rssreader/service/FolderServiceTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#59 게시글 파싱 로직 비동기 처리 후 깨진 테스트 수정
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
Labels: 🧑🏻‍💻 backend, ✅ test, 🚨 bug

#63 Folder Controller, Service를 읽기, 수정으로 분리
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/UpdateFolderController.java
  src/main/java/com/flytrap/rssreader/service/FolderReadService.java
  src/main/java/com/flytrap/rssreader/service/FolderUpdateService.java
  src/test/java/com/flytrap/rssreader/RssReaderApplicationTests.java
  src/test/java/com/flytrap/rssreader/service/FolderServiceTest.java
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
Labels: 🧑🏻‍💻 backend, 🚨 bug, 🛠 setting

#67 게시글 리스트 보기 및 필터링 기능 및 API 추가
  .gitignore
  build.gradle
  src/main/java/com/flytrap/rssreader/domain/post/Post.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/bookmark/BookmarkEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/OpenEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadDslRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/PostFilter.java
  src/main/java/com/flytrap/rssreader/presentation/dto/PostResponse.java
  src/main/java/com/flytrap/rssreader/service/PostListReadService.java
  src/main/resources/db/data.sql
  src/main/resources/db/schema.sql
Labels: 🧑🏻‍💻 backend, ✨ feature

#71 북마크 리스트 불러오기 기능 및 API 추가
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadDslRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/BookmarkController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/PostFilter.java
  src/main/java/com/flytrap/rssreader/service/BookmarkService.java
  src/main/java/com/flytrap/rssreader/service/PostListReadService.java
  src/main/resources/db/data.sql
  src/main/resources/db/schema.sql
Labels: 🧑🏻‍💻 backend, ✨ feature

#74 블로그 구독하기 기능 추가
  build.gradle
  src/main/java/com/flytrap/rssreader/domain/subscribe/BlogPlatform.java
  src/main/java/com/flytrap/rssreader/domain/subscribe/Subscribe.java
  src/main/java/com/flytrap/rssreader/global/config/EmbeddedRedisConfig.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssChecker.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/folder/FolderSubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/FolderSubscribeEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/SubscribeEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/RssFeedData.java
  src/main/java/com/flytrap/rssreader/presentation/dto/SubscribeRequest.java
  src/main/java/com/flytrap/rssreader/service/FolderSubscribeService.java
  src/main/java/com/flytrap/rssreader/service/SubscribeService.java
  src/main/resources/db/schema.sql
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#77 fix: 스키마, 데이터 엔티티 수정 (#68)
  src/main/java/com/flytrap/rssreader/infrastructure/entity/folder/FolderSubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/resources/db/data.sql
  src/main/resources/db/schema.sql
Labels: 🧑🏻‍💻 backend, 🚨 bug

#79 북마크 추가, 삭제 기능, API 구현
  src/main/java/com/flytrap/rssreader/domain/bookmark/Bookmark.java
  src/main/java/com/flytrap/rssreader/global/exception/DuplicateDomainException.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/bookmark/BookmarkEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/BookmarkEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/BookmarkController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/BookmarkRequest.java
  src/main/java/com/flytrap/rssreader/service/BookmarkService.java
  src/main/java/com/flytrap/rssreader/service/BookmarkVerifyOwnerService.java
  src/main/java/com/flytrap/rssreader/service/PostListReadService.java
  src/main/java/com/flytrap/rssreader/service/PostService.java
  src/main/resources/db/data.sql
Labels: 🧑🏻‍💻 backend, ✨ feature

#85 피드백 반영 구독 취소 테스트 코드추가
  src/main/java/com/flytrap/rssreader/infrastructure/repository/FolderSubscribeEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/service/FolderSubscribeService.java
  src/main/java/com/flytrap/rssreader/service/SubscribeService.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
  src/test/java/com/flytrap/rssreader/infrastructure/api/RssCheckerTest.java
  src/test/java/com/flytrap/rssreader/service/SubscribeServiceTest.java
Labels: 🧑🏻‍💻 backend, ✅ test

#88 포스트 열림 처리 Event/Service/Repository 구현
  build.gradle
  src/main/java/com/flytrap/rssreader/RssReaderApplication.java
  src/main/java/com/flytrap/rssreader/domain/post/PostOpenEvent.java
  src/main/java/com/flytrap/rssreader/global/event/EventHolder.java
  src/main/java/com/flytrap/rssreader/global/event/PublishEvent.java
  src/main/java/com/flytrap/rssreader/global/event/PublishEventAspect.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadDslRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostOpenRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostReadController.java
  src/main/java/com/flytrap/rssreader/service/PostOpenEventHandler.java
  src/main/java/com/flytrap/rssreader/service/PostOpenService.java
  src/main/java/com/flytrap/rssreader/service/PostReadService.java
  src/main/java/com/flytrap/rssreader/service/dto/PostOpenParam.java
  src/main/resources/db/schema.sql
  src/test/java/com/flytrap/rssreader/global/event/PublishEventAspectTest.java
  src/test/java/com/flytrap/rssreader/service/PostOpenEventHandlerTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#90 리액션 추가, 삭제 API작성
  src/main/java/com/flytrap/rssreader/infrastructure/entity/reaction/ReactionEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/ReactionEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/ReactionRequest.java
  src/main/java/com/flytrap/rssreader/service/ReactionService.java
  src/main/resources/db/schema.sql
  src/test/java/com/flytrap/rssreader/service/ReactionServiceTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#93 게시글 수집 시 구독한 블로그 제목도 같이 업데이트 하도록 변경
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssPostParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssItemResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssSubscribeResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssSubscribeTagName.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#94 폴더 리스트 반환시 함께 반환하는 부가 정보 추가
  src/main/java/com/flytrap/rssreader/domain/folder/Folder.java
  src/main/java/com/flytrap/rssreader/domain/folder/FolderSubscribe.java
  src/main/java/com/flytrap/rssreader/domain/shared/SharedFolder.java
  src/main/java/com/flytrap/rssreader/domain/subscribe/Subscribe.java
  src/main/java/com/flytrap/rssreader/global/event/PublishEventAspect.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/FolderSubscribeEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostOpenRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/SubscribeEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/FolderListSummary.java
  src/main/java/com/flytrap/rssreader/presentation/dto/Folders.java
  src/main/java/com/flytrap/rssreader/presentation/dto/MemberSummary.java
  src/main/java/com/flytrap/rssreader/presentation/dto/SubscribeListSummary.java
  src/main/java/com/flytrap/rssreader/presentation/facade/InvitedToFolderFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/MyFolderFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/OpenCheckFacade.java
  src/main/java/com/flytrap/rssreader/presentation/facade/SubscribeInFolderFacade.java
  src/main/java/com/flytrap/rssreader/service/FolderReadService.java
  src/main/java/com/flytrap/rssreader/service/FolderSubscribeService.java
  src/main/java/com/flytrap/rssreader/service/PostOpenService.java
  src/main/java/com/flytrap/rssreader/service/PostReadService.java
  src/main/java/com/flytrap/rssreader/service/SharedFolderReadService.java
  src/main/java/com/flytrap/rssreader/service/SubscribeService.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#96 게시글 수집 시 블로그 플랫폼 마다 상이한 pubDate 공통 처리
  src/main/java/com/flytrap/rssreader/global/utill/DateConvertor.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssPostParser.java
  src/main/resources/db/data.sql
  src/test/java/com/flytrap/rssreader/global/utill/DateConvertorTest.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#97 게시글 수집 시 썸네일 이미지도 수집하도록 변경
  build.gradle
  src/main/java/com/flytrap/rssreader/domain/post/Post.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/HTMLImageParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssPostParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssSubscribeResource.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/presentation/dto/PostResponse.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/resources/db/schema.sql
Labels: 🧑🏻‍💻 backend, ✨ feature
