Repository FlytrapHub/RSS-Reader, pull requests merged in 2024-01, with the labels that each got.

#144 구독 추가 API 수정 - 블로그 추가 성공시 블로그 정보를 반환하도록 수정
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/EmptyOpenPostCount.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/EmptySubscribePostCount.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/FolderUpdateControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/dto/SubscribeRequest.java
  src/main/java/com/flytrap/rssreader/presentation/facade/OpenCheckFacade.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#146 폴더에 회원 초대하기 API 수정 - 추가 성공시 회원 정보를 반환하도록 수정
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/SharedFolderUpdateControllerApi.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#148 폴더 목록 불러오기 API 수정 - 공유 폴더에 구독 블로그가 누락된 채로 폴더 목록이 반환되는 문제 해결
  src/main/java/com/flytrap/rssreader/domain/shared/SharedFolder.java
Labels: 🧑🏻‍💻 backend, 🚨 bug

#153 폴더에 멤버 추가하기 API 수정 - 폴더 소유자 초대 실패 시 개인 폴더가 공유폴더로 바뀌는 문제
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
Labels: 🧑🏻‍💻 backend, 🚨 bug

#158 로그인시 반환되는 회원정보 추가 및 간단한 로그인 버그 해결
  src/main/java/com/flytrap/rssreader/domain/member/Member.java
  src/main/java/com/flytrap/rssreader/infrastructure/properties/AdminProperties.java
  src/main/java/com/flytrap/rssreader/presentation/controller/AdminController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/AuthController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/AdminControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/controller/api/AuthControllerApi.java
  src/main/java/com/flytrap/rssreader/presentation/dto/LoginResponse.java
  src/main/java/com/flytrap/rssreader/presentation/filter/AuthenticationFilter.java
  src/main/java/com/flytrap/rssreader/presentation/filter/ExceptionHandleFilter.java
  src/main/java/com/flytrap/rssreader/service/AuthService.java
Labels: 🧑🏻‍💻 backend, 🚨 bug, ✨ feature

#162 PR#155 리뷰 반영 - toPrivate 메서드명을 makePrivate로 네이밍 규칙에 맞게 변경
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderUpdateService.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#163 폴더 멤버 제거, 폴더 떠나기 후 멤버가 남아 있어도 개인 폴더로 변환되는 문제 해결
  src/main/java/com/flytrap/rssreader/infrastructure/repository/SharedFolderJpaRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
  src/main/java/com/flytrap/rssreader/service/SharedFolderReadService.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#176 feat: AWS ALB를 위한 Health Check API 추가
  src/main/java/com/flytrap/rssreader/presentation/controller/HealthCheckController.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#179 Release용 머지
  nginx/conf.d/nginx.conf
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
  src/main/java/com/flytrap/rssreader/presentation/controller/HealthCheckController.java
Labels: 🧑🏻‍💻 backend, 🌟 release

#180 CORS 설정한 프론트 배포 주소에 www. 추가
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#181 Release용 머지
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
Labels: 🧑🏻‍💻 backend, 🌟 release

#182 CORS allowedOrigins 모두 전체 허용
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#183 Release용 머지
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
Labels: ⚙️ infrastructure, 🌟 release

#184 CORS 필터 추가 및 기존 필터 순서 변경
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
  src/main/java/com/flytrap/rssreader/presentation/filter/AuthenticationFilter.java
  src/main/java/com/flytrap/rssreader/presentation/filter/CorsFilter.java
Labels: 🧑🏻‍💻 backend, ⚙️ infrastructure

#185 Release용 머지
  src/main/java/com/flytrap/rssreader/global/config/WebConfig.java
  src/main/java/com/flytrap/rssreader/presentation/filter/AuthenticationFilter.java
  src/main/java/com/flytrap/rssreader/presentation/filter/CorsFilter.java
Labels: 🧑🏻‍💻 backend, 🌟 release

#186 Release용 GitHub Registry 는 어느 브랜치에서 배포되는가?
  docker-compose.yml
  nginx/conf.d/nginx.conf
  run.sh
  src/main/java/com/flytrap/rssreader/presentation/filter/CorsFilter.java
  src/main/java/com/flytrap/rssreader/presentation/filter/ExceptionHandleFilter.java
Labels: 🧑🏻‍💻 backend, 🌟 release

#171 docs: 리드미 기본틀 작성 (#170)
  README.md
Labels: 📃 documentation
