Repository FlytrapHub/RSS-Reader, pull requests merged in 2024-05, with the labels that each got.

#235 도메인 모델 및 프로젝트 구조 리팩토링 (folder) 2
  src/main/java/com/flytrap/rssreader/api/account/business/service/AccountService.java
  src/main/java/com/flytrap/rssreader/api/account/domain/AccountId.java
  src/main/java/com/flytrap/rssreader/api/auth/business/service/AuthService.java
  src/main/java/com/flytrap/rssreader/api/auth/presentation/controller/AdminController.java
  src/main/java/com/flytrap/rssreader/api/auth/presentation/controller/AuthController.java
  src/main/java/com/flytrap/rssreader/api/auth/presentation/controller/swagger/AdminControllerApi.java
  src/main/java/com/flytrap/rssreader/api/auth/presentation/controller/swagger/AuthControllerApi.java
  src/main/java/com/flytrap/rssreader/api/auth/presentation/dto/LoginResponse.java
  src/main/java/com/flytrap/rssreader/api/auth/presentation/dto/SignInResponse.java
  src/main/java/com/flytrap/rssreader/api/folder/business/service/FolderReadService.java
  src/main/java/com/flytrap/rssreader/api/folder/business/service/FolderUpdateService.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/AccessibleFolder.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/AccessibleFolders.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/Folder.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/FolderAggregate.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/FolderCreate.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/FolderDomain.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/PrivateFolder.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/SharedFolder.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/entity/FolderEntity.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/implementatioin/FolderCommand.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/implementatioin/FolderQuery.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/implementatioin/FolderValidation.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/repository/FolderEntityDslRepository.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/repository/FolderEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/dto/FolderUpdateResponse.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/dto/MyFoldersResponse.java
  src/main/java/com/flytrap/rssreader/api/member/domain/AccountId.java
  src/main/java/com/flytrap/rssreader/api/post/business/event/PostOpenEvent.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostListReadService.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostReadService.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostUpdateService.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/entity/BookmarkEntity.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/entity/OpenEntity.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/implementation/PostCommand.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/implementation/PostQuery.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/PostReadController.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/PostUpdateController.java
  src/main/java/com/flytrap/rssreader/global/exception/domain/ForbiddenAccessFolderException.java
  src/test/java/com/flytrap/rssreader/api/account/business/service/AccountServiceTest.java
  src/test/java/com/flytrap/rssreader/api/post/business/service/PostListReadServiceTest.java
  src/test/java/com/flytrap/rssreader/api/post/business/service/PostReadServiceTest.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#236 도메인 모델 및 프로젝트 구조 리팩토링 (folder-subscription)
  src/main/java/com/flytrap/rssreader/api/folder/business/service/FolderSubscribeService.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/FolderDomain.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/FolderSubscribe.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/swagger/FolderReadControllerApi.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/swagger/FolderUpdateControllerApi.java
  src/main/java/com/flytrap/rssreader/api/parser/RssSubscribeParser.java
  src/main/java/com/flytrap/rssreader/api/post/business/event/PostCollectEvent.java
  src/main/java/com/flytrap/rssreader/api/post/business/event/PostCollectEventListener.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostReadService.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/collect/PostCollectService.java
  src/main/java/com/flytrap/rssreader/api/subscribe/business/facade/SubscribeInFolderFacade.java
  src/main/java/com/flytrap/rssreader/api/subscribe/business/service/SubscribeService.java
  src/main/java/com/flytrap/rssreader/api/subscribe/business/service/SubscriptionService.java
  src/main/java/com/flytrap/rssreader/api/subscribe/domain/FolderSubscription.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/entity/FolderSubscribeEntity.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/implement/FolderSubscriptionCommand.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/implement/FolderSubscriptionValidator.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/repository/FolderSubscriptionDslRepository.java
  src/main/java/com/flytrap/rssreader/api/subscribe/presentation/controller/SubscriptionController.java
  src/main/java/com/flytrap/rssreader/api/subscribe/presentation/controller/swagger/SubscriptionControllerApi.java
  src/main/java/com/flytrap/rssreader/api/subscribe/presentation/dto/AddSubscriptionRequest.java
  src/main/java/com/flytrap/rssreader/api/subscribe/presentation/dto/SubscriptionResponse.java
  src/main/java/com/flytrap/rssreader/global/event/GlobalEventPublisher.java
  src/main/java/com/flytrap/rssreader/global/exception/domain/DuplicateDomainException.java
  src/main/java/com/flytrap/rssreader/global/exception/domain/ForbiddenAccessFolderException.java
  src/test/java/com/flytrap/rssreader/infrastructure/api/parser/RssSubscribeParserTest.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#238 도메인 모델 및 프로젝트 구조 리팩토링 (alert)
  src/main/java/com/flytrap/rssreader/api/alert/business/service/AlertService.java
  src/main/java/com/flytrap/rssreader/api/alert/domain/Alert.java
  src/main/java/com/flytrap/rssreader/api/alert/domain/AlertCreate.java
  src/main/java/com/flytrap/rssreader/api/alert/domain/AlertId.java
  src/main/java/com/flytrap/rssreader/api/alert/infrastructure/entity/AlertEntity.java
  src/main/java/com/flytrap/rssreader/api/alert/infrastructure/implement/AlertCommand.java
  src/main/java/com/flytrap/rssreader/api/alert/infrastructure/implement/AlertQuery.java
  src/main/java/com/flytrap/rssreader/api/alert/infrastructure/implement/AlertValidator.java
  src/main/java/com/flytrap/rssreader/api/alert/presentation/controller/AlertController.java
  src/main/java/com/flytrap/rssreader/api/alert/presentation/controller/swagger/AlertControllerApi.java
  src/main/java/com/flytrap/rssreader/api/folder/business/service/FolderVerifyService.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#239 도메인 모델 및 프로젝트 구조 리팩토링 (system)
  src/main/java/com/flytrap/rssreader/api/alert/business/event/NewPostAlertEvent.java
  src/main/java/com/flytrap/rssreader/api/alert/business/event/NewPostAlertEventHandler.java
  src/main/java/com/flytrap/rssreader/api/alert/business/event/NewPostAlertEventHolder.java
  src/main/java/com/flytrap/rssreader/api/alert/business/event/NewPostAlertEventListener.java
  src/main/java/com/flytrap/rssreader/api/alert/business/event/NewPostAlertEventPublisher.java
  src/main/java/com/flytrap/rssreader/api/alert/business/service/AlertService.java
  src/main/java/com/flytrap/rssreader/api/alert/domain/Alert.java
  src/main/java/com/flytrap/rssreader/api/alert/infrastructure/entity/AlertEntity.java
  src/main/java/com/flytrap/rssreader/api/alert/infrastructure/system/AlertSendSystem.java
  src/main/java/com/flytrap/rssreader/api/alert/presentation/dto/AlertResponse.java
  src/main/java/com/flytrap/rssreader/api/folder/business/service/FolderReadService.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/AccessibleFolders.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/Folder.java
  src/main/java/com/flytrap/rssreader/api/folder/domain/FolderDomain.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/entity/FolderEntity.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/implementatioin/FolderCommand.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/implementatioin/FolderQuery.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/dto/MyFoldersResponse.java
  src/main/java/com/flytrap/rssreader/api/post/business/event/PostCollectEventListener.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostCollectScheduledService.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostListReadService.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/collect/CollectPriority.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/system/CollectPriority.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/system/PostCollectSystem.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/system/SubscribeCollectionPriorityBlockingQueue.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/system/SubscribeCollectionPriorityQueue.java
  src/main/java/com/flytrap/rssreader/api/shared_member/business/service/SharedMemberService.java
  src/main/java/com/flytrap/rssreader/api/subscribe/business/service/SubscriptionService.java
  src/main/java/com/flytrap/rssreader/global/event/GlobalEventPublisher.java
  src/test/java/com/flytrap/rssreader/api/post/business/service/PostListReadServiceTest.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#244 구독별 게시글 불러오기 API 버그 수정 - 다른 구독의 게시글을 불러오는 문제
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostListReadService.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/api/subscribe/domain/Subscription.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/entity/SubscriptionEntity.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/implement/SubscriptionQuery.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/output/SubscriptionOutput.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/repository/SubscriptionDslRepository.java
Labels: 🧑🏻‍💻 backend, 🚨 bug

#245 Release용 머지 - Subscription별 Post보기 API 버그 수정 후 배포
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostListReadService.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/api/subscribe/domain/Subscription.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/entity/SubscriptionEntity.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/implement/SubscriptionQuery.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/output/SubscriptionOutput.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/repository/SubscriptionDslRepository.java
Labels: 🧑🏻‍💻 backend, 🌟 release

#247 API URL중 rss를 subscriptions로 변경
  src/main/java/com/flytrap/rssreader/api/subscribe/presentation/controller/SubscriptionController.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#251 게시글 수집 한 사이클만 실행하기 API 추가
  src/main/java/com/flytrap/rssreader/api/admin/business/service/AdminSystemService.java
  src/main/java/com/flytrap/rssreader/api/admin/presentation/controller/AdminController.java
  src/main/java/com/flytrap/rssreader/api/admin/presentation/dto/PostCollectionCycleRequest.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostCollectScheduledService.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/system/PostCollectSystem.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/system/PostCollectionEnableLoader.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#253 게시글 수집 스케쥴 시간 변경 API 추가
  src/main/java/com/flytrap/rssreader/api/admin/business/service/AdminSystemService.java
  src/main/java/com/flytrap/rssreader/api/admin/domain/AdminSystemAggregate.java
  src/main/java/com/flytrap/rssreader/api/admin/infrastructure/entity/AdminSystemEntity.java
  src/main/java/com/flytrap/rssreader/api/admin/infrastructure/implementation/AdminSystemCommand.java
  src/main/java/com/flytrap/rssreader/api/admin/infrastructure/system/PostCollectionEnableLoader.java
  src/main/java/com/flytrap/rssreader/api/admin/presentation/controller/AdminController.java
  src/main/java/com/flytrap/rssreader/api/admin/presentation/dto/PostCollectionDelayRequest.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostCollectScheduledService.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/system/PostCollectSystem.java
Labels: 🧑🏻‍💻 backend, ✨ feature

#266 batch 쿼리 수정
  .github/workflows/deploy-to-ec2.yml
  deploy.sh
  docker-compose.yml
  nginx/conf.d/nginx.conf
  run.sh
  src/main/java/com/flytrap/rssreader/global/batch/step/StatItemReader.java
  src/main/java/com/flytrap/rssreader/global/config/SchedulerConfig.java
Labels: 🧑🏻‍💻 backend, 🚨 bug

#264 Folder 2차 리펙토링 및 테스트 추가
  build.gradle
  src/main/java/com/flytrap/rssreader/api/alert/business/event/NewPostAlertEventListener.java
  src/main/java/com/flytrap/rssreader/api/folder/business/service/FolderCommandService.java
  src/main/java/com/flytrap/rssreader/api/folder/business/service/FolderQueryService.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/implementatioin/FolderCommand.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/implementatioin/FolderQuery.java
  src/main/java/com/flytrap/rssreader/api/folder/infrastructure/repository/FolderJpaRepository.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/FolderCommandController.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/FolderQueryController.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/swagger/FolderCommandControllerApi.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/controller/swagger/FolderQueryControllerApi.java
  src/main/java/com/flytrap/rssreader/api/folder/presentation/dto/FolderUpdateRequest.java
  src/main/java/com/flytrap/rssreader/api/shared_member/business/service/SharedMemberService.java
  src/main/java/com/flytrap/rssreader/global/exception/GlobalExceptionHandler.java
  src/main/resources/db/schema.sql
  src/test/java/com/flytrap/rssreader/CustomControllerTest.java
  src/test/java/com/flytrap/rssreader/CustomServiceTest.java
  src/test/java/com/flytrap/rssreader/RssReaderApplicationTests.java
  src/test/java/com/flytrap/rssreader/api/folder/business/service/FolderCommandServiceTest.java
  src/test/java/com/flytrap/rssreader/api/folder/business/service/FolderQueryServiceTest.java
  src/test/java/com/flytrap/rssreader/api/folder/presentation/controller/FolderCommandControllerTest.java
  src/test/java/com/flytrap/rssreader/api/folder/presentation/controller/FolderQueryControllerTest.java
  src/test/resources/application.yml
  src/test/resources/db/data.sql
  src/test/resources/reset.sql
Labels: 🧑🏻‍💻 backend, ✅ test, ♻️ refactor

#268 Post 2차 리펙토링 및 테스트 추가
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostCommandService.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostListQueryService.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostQueryService.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/implementation/PostCommand.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/implementation/PostQuery.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/repository/PostDslRepository.java
  src/main/java/com/flytrap/rssreader/api/post/infrastructure/repository/PostDslRepositoryImpl.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/PostCommandController.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/PostListQueryController.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/PostQueryController.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/swagger/PostCommandControllerApi.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/swagger/PostListQueryControllerApi.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/controller/swagger/PostQueryControllerApi.java
  src/main/java/com/flytrap/rssreader/api/post/presentation/dto/response/PostResponse.java
  src/test/java/com/flytrap/rssreader/api/post/PostScriptSql.java
  src/test/java/com/flytrap/rssreader/api/post/business/service/PostCommandServiceTest.java
  src/test/java/com/flytrap/rssreader/api/post/business/service/PostListQueryServiceTest.java
  src/test/java/com/flytrap/rssreader/api/post/business/service/PostQueryServiceTest.java
  src/test/java/com/flytrap/rssreader/api/post/presentation/controller/PostCommandControllerTest.java
  src/test/java/com/flytrap/rssreader/api/post/presentation/controller/PostQueryControllerTest.java
  src/test/resources/db/post-sample.sql
Labels: 🧑🏻‍💻 backend, ✅ test, ♻️ refactor

#269 Subscription 2차 리팩토링 및 테스트 추가
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostListQueryService.java
  src/main/java/com/flytrap/rssreader/api/post/business/service/PostQueryService.java
  src/main/java/com/flytrap/rssreader/api/subscribe/business/service/SubscriptionCommandService.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/implement/RssSourceQuery.java
  src/main/java/com/flytrap/rssreader/api/subscribe/infrastructure/implement/SubscriptionQuery.java
  src/main/java/com/flytrap/rssreader/api/subscribe/presentation/controller/SubscriptionCommandController.java
  src/main/java/com/flytrap/rssreader/api/subscribe/presentation/controller/swagger/SubscriptionCommandControllerApi.java
  src/test/java/com/flytrap/rssreader/api/subscribe/business/service/SubscriptionCommandServiceTest.java
  src/test/java/com/flytrap/rssreader/api/subscribe/presentation/controller/SubscriptionCommandControllerTest.java
Labels: 🧑🏻‍💻 backend, ✅ test, ♻️ refactor

#270 Alert 2차 리펙토링 및 테스트 추가
  src/main/java/com/flytrap/rssreader/api/alert/business/service/AlertCommandService.java
  src/main/java/com/flytrap/rssreader/api/alert/business/service/AlertQueryService.java
  src/main/java/com/flytrap/rssreader/api/alert/presentation/controller/AlertCommandController.java
  src/main/java/com/flytrap/rssreader/api/alert/presentation/controller/AlertQueryController.java
  src/main/java/com/flytrap/rssreader/api/alert/presentation/controller/swagger/AlertCommandControllerApi.java
  src/main/java/com/flytrap/rssreader/api/alert/presentation/controller/swagger/AlertQueryControllerApi.java
  src/test/java/com/flytrap/rssreader/api/alert/business/service/AlertCommandServiceTest.java
  src/test/java/com/flytrap/rssreader/api/alert/business/service/AlertQueryServiceTest.java
  src/test/java/com/flytrap/rssreader/api/alert/presentation/controller/AlertCommandControllerTest.java
  src/test/java/com/flytrap/rssreader/api/alert/presentation/controller/AlertQueryControllerTest.java
  src/test/java/com/flytrap/rssreader/api/post/business/service/PostListReadServiceTest.java
  src/test/java/com/flytrap/rssreader/api/post/business/service/PostReadServiceTest.java
  src/test/resources/application.yml
Labels: 🧑🏻‍💻 backend, ✅ test, ♻️ refactor
