Repository FlytrapHub/RSS-Reader, pull requests merged in 2024-02, with the labels that each got.

#188 프로젝트 배포 후 변경사항 sprint에 적용
  .github/workflows/deploy-to-ec2.yml
  nginx/conf.d/nginx.conf
  src/main/java/com/flytrap/rssreader/infrastructure/api/AuthGithubProvider.java
  src/main/java/com/flytrap/rssreader/presentation/controller/HealthCheckController.java
  src/main/java/com/flytrap/rssreader/presentation/filter/CorsFilter.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor, 🌟 release

#190 폴더 삭제시 폴더에 구독하고 있던 블로그가 여전히 남아있는 문제 해결
  src/main/java/com/flytrap/rssreader/infrastructure/repository/FolderSubscribeEntityJpaRepository.java
  src/main/java/com/flytrap/rssreader/infrastructure/repository/PostListReadDslRepository.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderSubscribeService.java
Labels: 🧑🏻‍💻 backend, 🚨 bug

#192 처음 블로그 구독하면 즉시 게시글을 수집하도록 변경
  src/main/java/com/flytrap/rssreader/domain/subscribe/Subscribe.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/folder/FolderSubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/java/com/flytrap/rssreader/service/SubscribeService.java
  src/test/java/com/flytrap/rssreader/fixture/SubscribeFixtureFactory.java
  src/test/java/com/flytrap/rssreader/service/SubscribeServiceTest.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor, ✨ feature

#198 폴더 포스트 리스트에 초대된 멤버가 접근할 수 없는 문제 해결
  src/main/java/com/flytrap/rssreader/global/exception/ForbiddenAccessFolderException.java
  src/main/java/com/flytrap/rssreader/global/exception/GlobalExceptionHandler.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderVerifyOwnerService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderVerifyService.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
  src/test/java/com/flytrap/rssreader/service/FolderVerifyOwnerServiceTest.java
  src/test/java/com/flytrap/rssreader/service/folder/FolderUpdateServiceTest.java
  src/test/java/com/flytrap/rssreader/service/folder/FolderVerifyServiceTest.java
Labels: 🚨 bug

#194 Tistory, Velog 외 다른 블로그 플랫폼의 RSS도 구독할 수 있도록 기능 변경
  src/main/java/com/flytrap/rssreader/domain/subscribe/BlogPlatform.java
  src/main/java/com/flytrap/rssreader/global/utill/DateConvertor.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/HTMLImageParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssChecker.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssDocumentParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssPostParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssItemTagName.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssSubscribeTagName.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssTag.java
  src/main/java/com/flytrap/rssreader/presentation/dto/RssFeedData.java
Labels: 🧑🏻‍💻 backend, 🚨 bug, ✨ feature

#195 RSS 문서 파싱 관련 모듈의 패키지 구조 및 네이밍 개선
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/HTMLImageParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/RssDocumentParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/RssPostParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/RssSubscribeParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/dto/RssPostsData.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/dto/RssSubscribeData.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/type/RssTag.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/presentation/dto/RssFeedData.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/java/com/flytrap/rssreader/service/SubscribeService.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
  src/test/java/com/flytrap/rssreader/infrastructure/api/parser/RssSubscribeParserTest.java
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
  src/test/java/com/flytrap/rssreader/service/SubscribeServiceTest.java
Labels: 🧑🏻‍💻 backend, ♻️ refactor

#199 배포용 머지 2024-02-10
  src/main/java/com/flytrap/rssreader/domain/subscribe/BlogPlatform.java
  src/main/java/com/flytrap/rssreader/domain/subscribe/Subscribe.java
  src/main/java/com/flytrap/rssreader/global/exception/ForbiddenAccessFolderException.java
  src/main/java/com/flytrap/rssreader/global/exception/GlobalExceptionHandler.java
  src/main/java/com/flytrap/rssreader/global/utill/DateConvertor.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssChecker.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/RssPostParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssItemTagName.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/dto/RssSubscribeTagName.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/HTMLImageParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/RssDocumentParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/RssPostParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/RssSubscribeParser.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/dto/RssPostsData.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/dto/RssSubscribeData.java
  src/main/java/com/flytrap/rssreader/infrastructure/api/parser/type/RssTag.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/folder/FolderSubscribeEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/post/PostEntity.java
  src/main/java/com/flytrap/rssreader/infrastructure/entity/subscribe/SubscribeEntity.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/FolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/PostListReadController.java
  src/main/java/com/flytrap/rssreader/presentation/controller/SharedFolderUpdateController.java
  src/main/java/com/flytrap/rssreader/presentation/dto/RssFeedData.java
  src/main/java/com/flytrap/rssreader/service/PostCollectService.java
  src/main/java/com/flytrap/rssreader/service/SubscribeService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderVerifyOwnerService.java
  src/main/java/com/flytrap/rssreader/service/folder/FolderVerifyService.java
  src/test/java/com/flytrap/rssreader/fixture/FixtureFactory.java
  src/test/java/com/flytrap/rssreader/fixture/SubscribeFixtureFactory.java
  src/test/java/com/flytrap/rssreader/infrastructure/api/parser/RssSubscribeParserTest.java
  src/test/java/com/flytrap/rssreader/service/FolderVerifyOwnerServiceTest.java
  src/test/java/com/flytrap/rssreader/service/PostCollectServiceTest.java
  src/test/java/com/flytrap/rssreader/service/SubscribeServiceTest.java
  src/test/java/com/flytrap/rssreader/service/folder/FolderUpdateServiceTest.java
  src/test/java/com/flytrap/rssreader/service/folder/FolderVerifyServiceTest.java
Labels: 🧑🏻‍💻 backend, 🌟 release
